config/routes.rb
Rails.application.routes.draw do
  root 'statics#top'
  get :dashboard, to: 'teams#dashboard'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  resource :user

  resources :teams do
    match "/assigns/:id" => "teams#owner", :as => :owner, via: :get
    resources :assigns, only: %w(create destroy)
    resources :agendas, shallow: true do
      resources :articles do
        resources :comments
      end
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
   before_action :set_agenda, only: %i[ destroy]

  def index
    @agendas = Agenda.all
  end
  def show
  end

  def new
    @team = Team.friendly.find(params[:team_id])
    @agenda = Agenda.new
  end

  def create
    @agenda = current_user.agendas.build(title: params[:title])
    @agenda.team = Team.friendly.find(params[:team_id])
    current_user.keep_team_id = @agenda.team.id
    if current_user.save && @agenda.save
      redirect_to dashboard_url, notice: I18n.t('views.messages.create_agenda')
    else
      render :new
    end
  end

  def destroy
   @agenda.destroy
   @agenda.team.assigns.each do |member|
     AgendaMailer.agenda_mail(member.user.email, @agenda.title).deliver
   end
   redirect_to dashboard_url, notice: "Agenda deleted!"
 end
   
  private

  def set_agenda
    @agenda = Agenda.find(params[:id])
  end

  def agenda_params
    params.fetch(:agenda, {}).permit %i[title description]
  end
end

app/controllers/assigns_controller.rb
class AssignsController < ApplicationController
  before_action :authenticate_user!
  before_action :email_exist?, only: [:create]
  before_action :user_exist?, only: [:create]

  def create
    team = find_team(params[:team_id])
    user = email_reliable?(assign_params) ? User.find_or_create_by_email(assign_params) : nil
    if user
      team.invite_member(user)
      redirect_to team_url(team), notice: I18n.t('views.messages.assigned')
    else
      redirect_to team_url(team), notice: I18n.t('views.messages.failed_to_assign')
    end
  end

  def destroy
    assign = Assign.find(params[:id])
    destroy_message = assign_destroy(assign, assign.user)

    redirect_to team_url(params[:team_id]), notice: destroy_message
  end

  private
  def assign_params
    params[:email]
  end

  def assign_destroy(assign, assigned_user)
    if assigned_user == assign.team.owner
      I18n.t('views.messages.cannot_delete_the_leader')
    elsif Assign.where(user_id: assigned_user.id).count == 1
      I18n.t('views.messages.cannot_delete_only_a_member')
    elsif current_user != assign.team.owner && current_user != assigned_user
    I18n.t('views.messages.cannot_delete_other_user')
    elsif assign.destroy
      set_next_team(assign, assigned_user)
      I18n.t('views.messages.delete_member')
    else
      I18n.t('views.messages.cannot_delete_member_4_some_reason')
    end
  end

  def email_exist?
    team = find_team(params[:team_id])
    if team.members.exists?(email: params[:email])
      redirect_to team_url(team), notice: I18n.t('views.messages.email_already_exists')
    end
  end

  def email_reliable?(address)
    address.match(/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i)
  end

  def user_exist?
    team = find_team(params[:team_id])
    unless User.exists?(email: params[:email])
      redirect_to team_url(team), notice: I18n.t('views.messages.does_not_exist_email')
    end
  end

  def set_next_team(assign, assigned_user)
    another_team = Assign.find_by(user_id: assigned_user.id).team
    change_keep_team(assigned_user, another_team) if assigned_user.keep_team_id == assign.team_id
  end

  def find_team(team_id)
    Team.friendly.find(params[:team_id])
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_team, only: %i[show edit update destroy]

  def index
    @teams = Team.all
  end

  def show
    @working_team = @team
    change_keep_team(current_user, @team)
  end

  def new
    @team = Team.new
  end

  def edit;
  end

  def create
    @team = Team.new(team_params)
    @team.owner = current_user
    if @team.save
      @team.invite_member(@team.owner)
      redirect_to @team, notice: I18n.t('views.messages.create_team')
    else
      flash.now[:error] = I18n.t('views.messages.failed_to_save_team')
      render :new
    end
  end
  def owner
      @team = Team.friendly.find(params[:team_id])
      new_owner = Assign.find(params[:id])
      @team.owner = new_owner.user
      @team.update(team_params)
      OwnerMailer.owner_mail(new_owner.user.email, @team.name).deliver
      redirect_to team_url(params[:team_id])
    end

  def update
    if @team.update(team_params)
      redirect_to @team, notice: I18n.t('views.messages.update_team')
    else
      flash.now[:error] = I18n.t('views.messages.failed_to_save_team')
      render :edit
    end
  end

  def destroy
    @team.destroy
    redirect_to teams_url, notice: I18n.t('views.messages.delete_team')
  end

  def dashboard
    @team = current_user.keep_team_id ? Team.find(current_user.keep_team_id) : current_user.teams.first
  end

  private

  def set_team
    @team = Team.friendly.find(params[:id])
  end

  def team_params
    params.fetch(:team, {}).permit %i[name icon icon_cache owner_id keep_team_id]
  end
end

app/views/shared/layout/_sidebar.html.erb
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <%= link_to dashboard_url, class: 'brand-link' do %>
    <span class="brand-text font-weight-light">DIVE INTO POST</span>
  <% end %>

  <!-- Sidebar -->
  <div class="sidebar">
    <div class="user-panel mt-3 pb-3 mb-3">
      <div class="info">
        <h3 style="color: white;"><%= @working_team.name.truncate(15) %></h3>
      </div>
    </div>

    <div class="user-panel mt-3 pb-3 mb-3">
      <div class="info">
        <a href="#" class="d-block mb-1"><%= I18n.t('views.messages.create_agenda') %></a>
        <%= form_with model: :agenda, scope: :post, url: team_agendas_path(@working_team), local: true do |form| %>
          <div class="input-group input-group-sm">
            <%= text_field_tag :title, '', { class: 'form-control', placeholder: I18n.t('views.messages.input_agenda_title') } %>
            <span class="input-group-append">
              <button type="submit" class="btn btn-info btn-flat"><%= I18n.t('views.button.create') %></button>
            </span>
          </div>
        <% end %>
      </div>
    </div>
    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <% @working_team.agendas.each do |agenda| %>
          <li class="nav-item has-treeview menu-open">
            <a href="#" class="nav-link">
              <i class="fa fa-circle-o nav-icon"></i>
              <p>
                <%= agenda.title %>
                <% if current_user.id == @working_team.owner_id || current_user.id == agenda.user_id %>
                  <%= link_to I18n.t('views.button.delete'), agenda, method: :delete, data: { confirm: 'Are you sure?' }%>
                <% end %>
                <i class="right fa fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview" style="display: block;">
              <% agenda.articles.each do |article| %>
                <li class="nav-item">
                  <%= link_to article_path(article), class: 'nav-link' do %>
                    <p><%= article.title %></p>
                  <% end %>
                </li>
              <% end %>
              <li class="nav-item">
                <%= link_to new_agenda_article_path(agenda), class: 'nav-link' do %>
                  <p>+ <%= I18n.t('views.messages.create_article') %></p>
                <% end %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>